### ISSUE TITLE
extract_todo_list not working.

### ISSUE THREAD

**Issue by rafaelleru** [bjonnh/PyOrgMode#31]
When I try to get the list of todos from a file I get nothing and I'm sure that file contains TODOs. I'm doing like this:

    def getTODOS():
        base = PyOrgMode.OrgDataStructure()
        base.load_from_file("index.org")

        print('archivo cargado')

        states = base.get_todo_states('todo')
        todos = base.extract_todo_list(states)
    
        for t in todos:
            print(t)`

it's an issue or is code error?

**Comment by madalu** [comment]
Reverting commit https://github.com/bjonnh/PyOrgMode/commit/880cdc2483b67236260d4e67c4d73a39ff4d1747 (as argarak mentioned in the linked pull request) fixed this issue for me. That commit broke detection of todo keywords.

**Comment by bjonnh** [comment]
@rafaelleru Can you test and tell me if you still have the issue? This should have been solved by the last merge I made.
