### ISSUE TITLE
Scheduled Todos dont have schedule date

### ISSUE THREAD

**Issue by brvier** [bjonnh/PyOrgMode#44]
Hi,

When loading a todo list, Todos don t have scheduled date even if there are in my todo file :

```
b = PyOrgMode.OrgDataStructure()
b.load_from_file('test.org')
for t in base.extract_todo_list():
    print(a.scheduled)
```

So i maybe not use it correctly ...

```
* TODO Test 1
SCHEDULED: <2018-09-25 Tue>
[2018-09-17 Mon 21:37]
```

**Comment by bjonnh** [comment]
Closed as it would be more relevant to use a maintained project such as https://github.com/karlicoss/orgparse .
