### ISSUE TITLE
PyPi version has no OrgDataStructure

### ISSUE THREAD

**Issue by Nalisarc** [bjonnh/PyOrgMode#48]
The pypi version seems to be out of data and lacks the OrgDataStructure class.
I fixed it by installing directly from git, but it would be nice to have a working pypi version for a requirements.txt file.

**Comment by Nalisarc** [comment]
That makes sense. I'll see if I can still make it useful. 
Thank you for the work you already put in.

**Comment by pinn3** [comment]
@Nalisarc The current version that's published on PyPi has an empty `__init__.py`.

This was changed in https://github.com/bjonnh/PyOrgMode/commit/cfd430afea3b1baad650c8bd0330474907b73f89#diff-6eacbfe2fc42bb76816707b3c985b428.

With the version on PyPi (0.1), you have to explicitly import PyOrgMode *from* PyOrgMode

```python
from PyOrgMode import PyOrgMode

org_structure = PyOrgMode.OrgDataStructure()
```
