### ISSUE TITLE
properties not saved in same sequence as original file

### ISSUE THREAD

**Issue by maxandersen** [bjonnh/PyOrgMode#49]
having fun with this library and I noticed that it doesn't keep the order of properties as found in original file.

original:
```
* DONE Call john
CLOSED: [2019-01-24 Thu 13:22] SCHEDULED: <2019-01-23 Wed 20:45>
```

new saved:
```
* DONE Call john
SCHEDULED: <2019-01-23 Wed 20:45> CLOSED: [2019-01-24 Thu 13:22]
```

is there a reason for this ? semantically it doesn't matter much for orgmode but it would be nice  this library could avoid being "destructive" in its edits.

**Comment by bjonnh** [comment]
Closed as it would be more relevant to use a maintained project such as https://github.com/karlicoss/orgparse .
