### ISSUE TITLE
alternatives to PyOrgMode?

### ISSUE THREAD

**Issue by rudolfolah** [bjonnh/PyOrgMode#50]
are there maintained alternatives to PyOrgMode or a fork that's maintained?

**Comment by flintforge** [comment]
Looking at the insights/network graph, there are a few commits ahead in other repos from nov 18.

Matter of taste, I made a pythonic rewrites in some sections. 
https://github.com/flintforge/pyorgmode
The work to achieve a fully functional parser is unreasonable.

The best alternative is org-mode itself

**Comment by rudolfolah** [comment]
Hmm, okay, I ended up checking out OrgNode.py, I may create a new github repo to host it as a mirror or something.

Thanks!
